### ISSUE TITLE
Python library for CMA-ES.

### ISSUE THREAD

**Issue by c-bata** [jgvictores/awesome-deep-reinforcement-learning#6]
Hi, I'm an author of https://github.com/CyberAgent/cmaes.

In this issue, I wanna ask about adding CyberAgent/cmaes in the "Evolutionary Algorithms (EA)" section.
The GitHub stars are still not so much, but it is used by [Optuna](https://github.com/optuna/optuna).
Can I open a pull request to add this library?

**Comment by jgvictores** [comment]
Hi, that would be excellent!

CMA-ES is a method I've been wanting to try for a long time, so it's great to add options!!

**Comment by c-bata** [comment]
Thank you for your response!

I've just opened a pull requst at https://github.com/jgvictores/awesome-deep-reinforcement-learning/pull/7 👍
